# -*- coding: utf-8 -*-
"""Global CO₂ Emissions Data Analysis and Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQgbJDmgofjHD8iMZqlBsz5L3Eik0lHh
"""

from google.colab import files
files.upload()
import pandas as pd
df = pd.read_csv("global_co2_extended.csv")

import pandas as pd

# Load the dataset
df = pd.read_csv('global_co2_extended.csv')

# Group by continent and calculate mean, min, and max CO2 emissions
continent_emissions = df.groupby('continent')['co2_emissions'].agg(['mean', 'min', 'max'])

# Display the results
print(continent_emissions)

# Filter data for 2000 and 2020
df_2000 = df[df['year'] == 2000]
df_2020 = df[df['year'] == 2020]

# Group by country and sum CO2 emissions
top_2000 = df_2000.groupby('country')['co2_emissions'].sum().sort_values(ascending=False).head(10)
top_2020 = df_2020.groupby('country')['co2_emissions'].sum().sort_values(ascending=False).head(10)

# Display the results
print("Top 10 CO2 Emitting Countries in 2000")
print(top_2000)
print("\nTop 10 CO2 Emitting Countries in 2020")
print(top_2020)

# Check for missing values in GDP and population
print(df[['gdp', 'population']].isnull().sum())

# Impute missing values with median (for both GDP and population)
df['gdp'] = df['gdp'].fillna(df['gdp'].median())
df['population'] = df['population'].fillna(df['population'].median())

# Verify that there are no more missing values
print(df[['gdp', 'population']].isnull().sum())

# Classify countries based on GDP per capita
df['gdp_per_capita'] = df['gdp'] / df['population']
df['country_status'] = df['gdp_per_capita'].apply(lambda x: 'Developed' if x > 20000 else 'Developing')

# Calculate per-capita emissions
df['per_capita_emissions'] = df['co2_emissions'] / df['population']

# Group by country_status and calculate mean per-capita emissions
status_emissions = df.groupby('country_status')['per_capita_emissions'].mean()

# Display the results
print(status_emissions)

import matplotlib.pyplot as plt

# Group by year and sum CO2 emissions
yearly_emissions = df.groupby('year')['co2_emissions'].sum()

# Plot the emission trends over time
plt.figure(figsize=(10, 6))
plt.plot(yearly_emissions.index, yearly_emissions.values, marker='o')
plt.title('Global CO₂ Emissions Over Time')
plt.xlabel('Year')
plt.ylabel('Total CO₂ Emissions (in billion tons)')
plt.grid(True)
plt.show()

import seaborn as sns

# Compute correlation matrix
corr = df[['co2_emissions', 'gdp', 'population']].corr()

# Create a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of CO₂ Emissions, GDP, and Population')
plt.show()